name: Java CI with Maven
on:
  push:
    branches: ['master']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file 'devops-labs-master/pom.xml'
      - name: Copy JAR to Docker context
        run: cp devops-labs-master/target/*.jar .
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          context: ./devops-labs-master/
          dockerfile: 'devops-labs-master/Dockerfile'
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: skerdishehaj/cloud-app-mpl
          tag_with_ref: true
